#!/bin/bash

pID="/tmp/pomodoro"

if [ ! -f "$pID" ]; then
	exit
fi

if [ "$BLOCK_BUTTON" -eq 1 ]; then
	if [ -z $(pgrep pomodoro_pause) ]; then
		notify-send -t 2 "Pomodoro" "Pomodoro Paused"
		nohup pomodoro_pause &>/dev/null &
	else
		notify-send -t 2 "Pomodoro" "Pomodoro Resumed"
		pomodoro_resume
	fi
elif [ "$BLOCK_BUTTON" -eq 3 ]; then
	pomodoro_stop
	echo "Stopping"
	echo
	echo "#FFFFFF"
fi

LINE="$(awk '/./{line=$0} END{print line}' $pID)"
TIME="$(echo $LINE | awk '{print $1}')"
STATUS="$(echo $LINE | awk '{print $2}')"

echo " $TIME";
echo " $TIME"

if [ $STATUS -eq 0 ]; then
	echo "#FF4545";
else
	echo "#45FF45";
fi

