[config]
reload_apps = false

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar-colors.css"
output_path = "~/.config/waybar/colors-matugen.css"
post_hook = "pkill -SIGUSR2 waybar"

[templates.rofi]
input_path = 'templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors-matugen.rasi'

[templates.dunst]
input_path = "templates/dunstrc-colors"
output_path = "~/.config/dunst/dunstrc"

[templates.swaylock]
input_path = "templates/swaylock"
output_path = "~/.config/sway/lock-config-matugen"

[templates.kitty]
input_path = 'templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors-matugen.conf'