#!/bin/bash

pID="/tmp/countdown"

if [ ! -f "$pID" ]; then
	exit
fi

if [ "$BLOCK_BUTTON" -eq 1 ]; then
	if [ -z $(pgrep countdown_pause) ]; then
		notify-send -t 2 "Countdown" "Countdown Paused"
		nohup countdown_pause &>/dev/null &
	else
		notify-send -t 2 "Countdown" "Countdown Resumed"
		countdown_resume
	fi
elif [ "$BLOCK_BUTTON" -eq 3 ]; then
	countdown_stop
	echo "Stopping"
	echo
	echo "#FFFFFF"
fi

TIME="$(awk '/./{line=$0} END{print line}' $pID)"

echo " $TIME";
echo " $TIME"
echo "#FFFFFF";
