#!/bin/bash

pID="/tmp/countdown"

if [ ! -f "$pID" ]; then
	exit
fi

if [ "$BLOCK_BUTTON" -eq 1 ]; then
	countdown_stop
	echo "Stopping"
	echo
	echo "#FFFFFF"
fi

TIME="$(awk '/./{line=$0} END{print line}' $pID)"

echo " $TIME";
echo " $TIME"
echo "#FFFFFF";
