#!/bin/bash

DEFAULT=$(pactl info | awk '/Default Sink/{print $3}')
INDEX=$(pactl list sinks short | awk "/$DEFAULT/"'{print $1}')

# Get Volume
VOLUME=$(pactl list sinks | grep "Sink #$INDEX\|^[[:space:]]Volume:" | grep -A 1 "Sink #$INDEX" | grep "^[[:space:]]Volume" | awk '{print $5}');

# Get Mute Status
MUTE=$(pactl list sinks | grep "Sink #$INDEX\|Mute" | grep -A 1 "Sink #$INDEX" | grep Mute | awk '/Mute/{print $2}')

ICON=
COLOR="#E0E0E0"

if [ $MUTE == "yes" ]; then
	ICON=
	COLOR="#E0E000"
fi

echo "$ICON  $VOLUME"
echo "$ICON  $VOLUME"
echo $COLOR
