#!/bin/bash

DEFAULT=$(pactl info | awk '/Default Sink/{print $3}')
INDEX=$(pactl list sinks short | awk "/$DEFAULT/"'{print $1}')

VOLUME=$(pactl list sinks | grep "Sink #$INDEX\|^[[:space:]]Volume:" | grep -A 1 "Sink #$INDEX" | grep "^[[:space:]]Volume" | awk '{print $5}');

echo $VOLUME
