#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

stty -ixon

alias ls='ls -h --color=auto'
PS1='[\u@\h \W]\$ '

export EDITOR=vim
export VISUAL=$EDITOR
export DOTFILES=$HOME/.dotfiles
export WINEPATH=$HOME/.wineFolder

PATH=$PATH:$DOTFILES/bin

HEADSET=alsa_output.usb-Logitech_Logitech_G430_Gaming_Headset-00.analog-stereo
MIC=alsa_input.pci-0000_00_1b.0.analog-stereo
