#!/bin/sh

BATTERY=$(acpi -b | grep "Charging")
if [[ -z $BATTERY ]]; then
    BATTERY=$(acpi -b | head -1)
fi


PERCENT=$(echo $BATTERY | awk '{ print $4 }' | grep -o '[0-9]\+' | head -1)
STATUS=$(echo $BATTERY | awk '{ print $3}' | cut -f 1 -d, | head -1)
TIME=$(echo $BATTERY | awk '{ print $5}' | grep '[0-9]\+:[0-9]\+:[0-9]\+' | head -1)

if [[ $PERCENT != "" ]]; then
    FULL_TEXT="$PERCENT%"

    if [[ $STATUS == 'Charging' ]]; then
        FULL_TEXT="$FULL_TEXT "
    fi

    SHORT_TEXT="$FULL_TEXT"

    if [[ $TIME != "" ]]; then
        FULL_TEXT="$FULL_TEXT ($TIME)"
    fi

    # print text
    echo " $FULL_TEXT"
    echo " $SHORT_TEXT"
fi

# consider color and urgent flag only on discharge
if [[ $STATUS == 'Discharging' ]]; then
	if [[ $PERCENT -lt 20 ]]; then
		echo "#FF4444"
    elif [[ $PERCENT -lt 40 ]]; then
		echo "#FFAE00"
    elif [[ $PERCENT -lt 60 ]]; then
		echo "#FFF600"
    elif [[ $PERCENT -lt 85 ]]; then
		echo "#A8FF00"
    fi
fi
