#!/bin/sh

case "$BLOCK_BUTTON" in
    2) yt-player ;;
    1) mpc toggle -q ;;
    3) mpc next -q ;;
    4) mpc volume -q +5 ;;
    5) mpc volume -q -5 ;;
esac


DEFAULT_COLOR=${DEFAULT_COLOR:-"#ffffff"}
MUTED_COLOR=${MUTED_COLOR:-"#dfdf32"}

CURRENT=$(mpc current | cut -d- -f2-)

if [ -z "$CURRENT" ]; then
    exit
fi

PLAYING=$(mpc | grep "\[playing\]")
if [ -z $PLAYING ]; then
    COLOR="$MUTED_COLOR"
else
    COLOR="$DEFAULT_COLOR"
fi

VOLUME=$(mpc | grep "volume:" | cut -d':' -f 2 | awk '{print $1}')

ICON=""
echo "$ICON $CURRENT ($VOLUME)"
echo "$ICON $VOLUME"
echo "$COLOR"
