#!/bin/bash

full=""
short=""

URL="https://www.accuweather.com/en/at/vienna/31868/weather-forecast/31868"

currently="$(curl $URL | awk -F= '/data-api= /')"
weather="$(echo "$currently" | grep "current_main_descr")"
temp="$(echo "$currently" | jq -r '.temperature')"
t=${temp:-"? "}

case "$weather" in
clear-day)
	icon="滛"
	color="#FFFF00"
	;;
clear-night)
	icon="望"
	color="#00bfff"
	;;
rain)
	icon="歹"
	color="#0088FF"
	;;
snow)
	icon="流"
	color="#82EAFF"
	;;
wind)
	icon="煮"
	color="#b0db6f"
	;;
fog)
	icon="敖"
	color="#b9c6a5"
	;;
cloudy)
	icon="摒"
	color="#969696"
	;;
partly-cloudy*)
	icon="杖"
	color="#d6ca9c"
	;;
*hail*)
	icon="晴"
	color="#64acc1"
	;;
*thunder*)
	icon="朗"
	color="#FFFAAA"
	;;
esac

full="$icon $t°"
short="$icon"

echo $full
echo $short
echo $color

if [[ "$BLOCK_BUTTON" -eq 1 ]]; then
	xdg-open "$URL"
fi
