#!/bin/sh

PERCENT=$(acpi -b | awk '{ print $4 }' | grep -o '[0-9]\+')
STATUS=$(acpi -b | awk '{ print $3}' | cut -f 1 -d,)
TIME=$(acpi -b | awk '{ print $5}' | grep '[0-9]\+:[0-9]\+:[0-9]\+')

FULL_TEXT="$PERCENT%"

if [ $STATUS == 'Charging' ]; then
	FULL_TEXT="$FULL_TEXT "
fi

SHORT_TEXT="$FULL_TEXT"

if [ $TIME != "" ]; then
    FULL_TEXT="$FULL_TEXT ($TIME)"
fi

# print text
echo "$FULL_TEXT"
echo "$SHORT_TEXT"

# consider color and urgent flag only on discharge
if [ $STATUS == 'Discharging' ]; then

	if [ $PERCENT < 20 ]; then
		echo "#FF4444"
    elif [ $PERCENT < 40 ]; then
		echo "#FFAE00"
    elif [ $PERCENT < 60]; then
		echo "#FFF600"
    elif [ $PERCENT < 85 ]; then
		echo "#A8FF00"
    fi
fi
