#!/bin/sh

case "$BLOCK_BUTTON" in
    2) mpc prev -q ;;
    1) mpc toggle -q ;;
    3) mpc next -q ;;
    4) mpc volume -q +5 ;;
    5) mpc volume -q -5 ;;
esac


DEFAULT_COLOR=${DEFAULT_COLOR:-"#ffffff"}
MUTED_COLOR=${MUTED_COLOR:-"#dfdf32"}

CURRENT=$(mpc current)
SHORT=$(mpc current | awk '{print $3, $4, $5}') # $1 and $2 is not part of title

if [ -z "$CURRENT" ]; then
    exit
fi

PLAYING=$(mpc | grep "\[playing\]")
if [ -z $PLAYING ]; then
    COLOR="$MUTED_COLOR"
else
    COLOR="$DEFAULT_COLOR"
fi

VOLUME=$(mpc | grep "volume: " | awk '{print $2}')

ICON=""
echo "$ICON $CURRENT ($VOLUME)"
echo "$ICON $SHORT"
echo "$COLOR"
