$lock_cmd = pidof hyprlock || hyprlock
$suspend_cmd = systemctl suspend || loginctl suspend

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch global quickshell:lockFocus
    inhibit_sleep = 3
}

listener {
    timeout = 300 # 5mins
    on-timeout = brightnessctl -s set 25
    on-resume = brightnessctl -r
}

listener {
    timeout = 360 # 6mins
    on-timeout = loginctl lock-session
}

listener {
    timeout = 480 # 8mins
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

listener {
    timeout = 600 # 10mins
    on-timeout = $suspend_cmd
}
