set autoread                " detect when a file is changed
set history=100             " change history to 100
set clipboard=unnamedplus
set encoding=utf-8
colorscheme wal

" Turn of Backup
set nobackup
set nowb
set noswapfile

" Use Better Colors + Mouse Support
set termguicolors
set mouse=a

" Syntax Highlighting
syntax on
au BufNewFile,BufRead *.aspx set syntax=aspvbs
au BufNewFile,BufRead *.cshtml set syntax=html
au BufNewFile,BufRead *.ts set syntax=typescript
au BufNewFile,BufRead *.qss set syntax=css

" Plugin Installer
execute pathogen#infect()
filetype plugin indent on

" Line Numbers and wrapping
set number                  " show line numbers
set relativenumber          " show relative line numbers
set wrap                    " turn on line wrapping
set linebreak               " set soft wrapping
set autoindent              " automatically set indent of new line
set showmatch               " show matching braces
set laststatus=2

" toggle invisible characters
set list
set listchars=tab:\|\ ,eol:¬,trail:⋅,extends:❯,precedes:❮
set showbreak=↪

" make backspace behave in a sane manner
set backspace=indent,eol,start

" Tab control
set noexpandtab             " insert tabs rather than spaces for <Tab>
set smarttab                " tab respects 'tabstop', 'shiftwidth', and 'softtabstop'
set tabstop=4               " the visible width of tabs
set shiftwidth=4            " number of spaces to use for indent and unindent
set softtabstop=4           " edit as if the tabs are 4 characters wide
set shiftround              " round indent to a multiple of 'shiftwidth'
set scrolloff=3             " lines of text around cursor

" Searching
set ignorecase              " case insensitive searching
set smartcase               " case-sensitive if expresson contains a capital letter
set hlsearch                " highlight search results
set incsearch               " set incremental search

" Ignore files
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.o	" MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe		" Windows
let g:ctrlp_custom_ignore = {
\ 'dir': 'node_modules\|database\|\v[\/]\.(git|hg|svn)$',
\ 'file': '\v\.(exe|so|dll|o)$',
\ }

"""""""""""""
" SHORTCUTS "
"""""""""""""

" Remove Highlight
noremap <space> :noh<cr>

" Equal Windows
"noremap <A-w> <C-w>=
noremap <C-s> :w<cr>

" Replace all tabs with 4 spaces
noremap <C-p> :%s/\t/\ \ \ \ /g<cr>

" Tabs
noremap <C-t> :tabnew<cr>
noremap <A-w> :tabclose<cr>
noremap <A-h> :tabN<cr>
noremap <A-l> :tabn<cr>

" scroll the viewport faster
noremap <C-d> 5<C-e>
noremap <C-u> 5<C-y>

vnoremap <C-c> "*y
