set autoread                " detect when a file is changed
set history=100             " change history to 100
set clipboard=unnamedplus
set encoding=utf-8
colorscheme base16-default-dark

" Turn of Backup
set nobackup
set nowb
set noswapfile

" Use Better Colors + Mouse Support
set termguicolors
set mouse=a

" Syntax Highlighting
syntax on
au BufNewFile,BufRead *.aspx set syntax=aspvbs
au BufNewFile,BufRead *.cshtml set syntax=html
au BufNewFile,BufRead *.ts set syntax=typescript

" Plugin Installer
execute pathogen#infect()
filetype plugin indent on

" Latex Live Preview
let g:livepreview_previewer = 'mupdf'
let g:livepreview_engine = 'lualatex'

" Line Numbers and wrapping
set number                  " show line numbers
set relativenumber          " show relative line numbers
set wrap                    " turn on line wrapping
set linebreak               " set soft wrapping
set autoindent              " automatically set indent of new line
set showmatch               " show matching braces
set laststatus=2

" toggle invisible characters
set list
set listchars=tab:\|\ ,eol:¬,trail:⋅,extends:❯,precedes:❮
set showbreak=↪

" make backspace behave in a sane manner
set backspace=indent,eol,start

" Tab control
set noexpandtab             " insert tabs rather than spaces for <Tab>
set smarttab                " tab respects 'tabstop', 'shiftwidth', and 'softtabstop'
set tabstop=4               " the visible width of tabs
set shiftwidth=4            " number of spaces to use for indent and unindent
set softtabstop=4           " edit as if the tabs are 4 characters wide
set shiftround              " round indent to a multiple of 'shiftwidth'
set scrolloff=3             " lines of text around cursor

" Searching
set ignorecase              " case insensitive searching
set smartcase               " case-sensitive if expresson contains a capital letter
set hlsearch                " highlight search results
set incsearch               " set incremental search

" Ignore files
set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.o	" MacOSX/Linux
set wildignore+=*\\tmp\\*,*.swp,*.zip,*.exe		" Windows
let g:ctrlp_custom_ignore = {
\ 'dir': 'node_modules\|database\|\v[\/]\.(git|hg|svn)$',
\ 'file': '\v\.(exe|so|dll|o)$',
\ }

" Change Netrw Style
let g:netrw_liststyle = 3
let g:netrw_banner = 0
let g:netrw_browse_split = 2
let g:netrw_altv = 1
let g:netrw_winsize = 25

" Fix incorrect BG Rendering in Kitty
if has('gui_running') || has('nvim')
    hi Normal 		guifg=#d8d8d8 guibg=#181818
else
    " Set the terminal default background and foreground colors, thereby
    " improving performance by not needing to set these colors on empty cells.
    hi Normal guifg=NONE guibg=NONE ctermfg=NONE ctermbg=NONE
    let &t_ti = &t_ti . "\033]10;#d8d8d8\007\033]11;#181818\007"
    let &t_te = &t_te . "\033]110\007\033]111\007"
endif

"""""""""""""
" SHORTCUTS "
"""""""""""""

" Remove Highlight
noremap <space> :noh<cr>

" Equal Windows
noremap <A-w> <C-w>=
noremap <C-s> :w<cr>

" Tabs
noremap <C-t> :tabnew<cr>
noremap <C-w> :tabclose<cr>
noremap <A-h> :tabN<cr>
noremap <A-l> :tabn<cr>

" scroll the viewport faster
noremap <C-d> 5<C-e>
noremap <C-u> 5<C-y>

" Detect <Alt> Key on some terminals by using <ESC>
let c='a'
while c <= 'z'
  exec "set <A-".c.">=\e".c
  exec "imap \e".c." <A-".c.">"
  let c = nr2char(1+char2nr(c))
endw

set timeout ttimeoutlen=50
