#!/bin/bash

pacman -S - < core

systemctl enable ntpd
systemctl enable slim

curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/package-query.tar.gz
tar -xvzf package-query.tar.gz
cd package-query
makepkg -si

cd ..
curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/yaourt.tar.gz
tar -xvzf yaourt.tar.gz
cd yaourt
makepkg -si

cd ..
rm package-query -r
rm yaourt -r
rm package-query.tar.gz
rm yaourt.tar.gz

pacman -Sy
pacman -S - < extra
